services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: am/bpoe-api-gateway:latest
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8080:8080"
